version: '3.5'

services:
  postgres:
    container_name: postgres
    restart: always
    ports:
      - "5436:5432" #"5438:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=users
    image: postgres:15.0-alpine3.16

  wallet-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./wallet-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - /.env
    #environment:
    #  - DB_PASSWORD=admin